### ISSUE TITLE
Recommended way to set ivfflat.probes in a docker image

### ISSUE THREAD

**Issue by JuanjoAlegria** [pgvector/pgvector#221]
Hi!

Before anything else, thank you for this amazing library. It's extremely useful.

I'm developing an application that stores about 30M of embeddings, so we set the number of lists accordingly when building the index. Our issue right now is how to permanently set the number of probes, considering that our application is distributed in a docker image. According to #167 , there are some options:
- Modify the postgresql.conf file
- ALTER SYSTEM
- ALTER DATABASE
But we are not sure about which way is the best/recommended way to do it in a docker image. Another alternative is to simply set the number of probes everytime we make a call, but that may be cumbersome. Can you help us please? Thanks!

Extra information:
- The application is written in django, and we are using the extension [pgvector-python](https://github.com/pgvector/pgvector-python). 
- We are using the [ankane/pgvector](https://hub.docker.com/r/ankane/pgvector) image for postgres.

**Comment by jkatz** [comment]
How are you setting the other PostgreSQL configuration parameters (e.g. `shared_buffers`)? I'd recommend setting it the same way you are managing the other configuration parameters.

**Comment by JuanjoAlegria** [comment]
Thanks! I'm passing those parameters directly in my docker-compose, but I didn't know that I could do the same with ivfflat.probes. 

In case anybody else is wondering, my dockerfile looks like this (and it works):
```
services:
  db:
    container_name: <CONTAINER_NAME>
    image: ankane/pgvector
    command:
      - "postgres"
      - "-c"
      - "maintenance_work_mem=8GB"
      . . .
      - "-c"
      - "ivfflat.probes=<N_PROBES>"
```
