### ISSUE TITLE
Install in windows not found vcvars64.bat

### ISSUE THREAD

**Issue by s-triar** [pgvector/pgvector#452]
in this https://github.com/pgvector/pgvector?tab=readme-ov-file#windows, windows user need to vcvars64.bat but I does not find that file in my Visual Studio 2022 folder installation.

This is what I've install in Visual Studio installer.
![image](https://github.com/pgvector/pgvector/assets/34316314/0130507a-f816-4ab6-bc27-36da0c7a915f)

**Comment by s-triar** [comment]
I also use this docker compose file but still error vector.control extension not found
```
version: "3.2"

services:

  pg:
    image: postgres
    container_name: test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data
    build:
      context: https://github.com/pgvector/pgvector.git#v0.5.1
      no_cache: true
      pull: true
    volumes:
      - ./pg:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

```
