### ISSUE TITLE
How to install pgvector with an existing postgres docker image?

### ISSUE THREAD

**Issue by niwaa** [pgvector/pgvector#56]
Sorry if this is trivial but I trying to get pgvector to work with my existing docker postgres container, and looking for some pointers.

I currently have a setup using `docker-compose`, which is running a `postgres` image and another service. 

$docker ps
```
CONTAINER ID   IMAGE                           COMMAND                   CREATED        STATUS        PORTS                                       NAMES
e1efada5776d   postgres                        "docker-entrypoint.s…"    3 years ago    Up 2 months   5432/tcp                                    hasura_postgres_1
...
```
I've pulled the pg-vector image.

$docker image ls
```
REPOSITORY              TAG              IMAGE ID       CREATED        SIZE
ankane/pgvector         latest           1865afc96f66   3 weeks ago    381MB
```

How do I add the extension into my existing postgres container?  The documentation mentions: "_**This adds pgvector to the Postgres image**_" but it is not clear what to do next.

Running SQL `CREATE EXTENSION vector;` inside postgresql will currently yield `"/usr/share/postgresql/12/extension/vector.control": No such file or directory.null` which seems expected as the extension files aren't there.

My docker-compose.yaml looks like this:

```
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql_service:
    image: graphql_service
    depends_on:
    - "postgres"
    restart: always
volumes:
  db_data:
```
