### ISSUE TITLE
Docker image not installing pgvector extension

### ISSUE THREAD

**Issue by citric-gabriel** [pgvector/pgvector#622]
Using python 3.11 and pytest to run.
Docker Image: pgvector/pgvector:0.7.2-pg16

Starting vector service from docker compose and trying to create table with vector type gives error
```        
# Create tables in tenant schemas
>       cursor.execute("""
        CREATE TABLE IF NOT EXISTS tenant1.items (
            id SERIAL PRIMARY KEY,
            embedding vector(300),
            sensitive_info TEXT
        );
        """)
E       psycopg2.errors.UndefinedObject: type "vector" does not exist
E       LINE 4:         embedding vector(300),
E         ```
```

trying to force the initialization of the extension gives the following:
```
        # Create extension
>       cursor.execute("CREATE EXTENSION IF NOT EXISTS pgvector;")
E       psycopg2.errors.FeatureNotSupported: extension "pgvector" is not available
E       DETAIL:  Could not open extension control file "/usr/share/postgresql/16/extension/pgvector.control": No such file or directory.
E       HINT:  The extension must first be installed on the system where PostgreSQL is running.
```

## Relevant files

```
#docker_compose.yml
services:
  vector:
    container_name: lil-chatty-vector-store
    image: pgvector/pgvector:0.7.2-pg16
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_USER: ${PGVECTOR_USER}
      POSTGRES_PASSWORD: ${PGVECTOR_PASSWORD}
      POSTGRES_DB: ${PGVECTOR_DB}
    volumes:
      - /opt/citric/vector-data:/var/lib/postgresql/data
      - ./resources/docker_compose_startup/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
```

```
#init.sql
-- Enable extensions
CREATE EXTENSION IF NOT EXISTS pgvector;
```
