### ISSUE TITLE
container-error: program "postgres" is needed by initdb but was not found

### ISSUE THREAD

**Issue by hobin2017** [pgvector/pgvector#826]
the docker-compose is given below.
```
version: '3'
services:
  postgres:
    image: pgvector/pgvector:pg16
    network_mode: host
    # restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxx123456789!!
    volumes:
      - /home/18data_pgvector:/var/lib/postgresql/data
```

the error goes here
```
Recreating vectordb_postgres_1 ... done
Attaching to vectordb_postgres_1
vectordb_postgres_1 | popen failure: Cannot allocate memory
vectordb_postgres_1 | initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/16/bin/initdb"
vectordb_postgres_1 exited with code 1
```
