### ISSUE TITLE
FATAL:  no pg_hba.conf entry for host "172.18.0.8" - Docker

### ISSUE THREAD

**Issue by fahadshery** [pgvector/pgvector#827]
Hi,

Here is my docker compose:

```
  postgres:
    image: pgvector/pgvector:pg17
    hostname: postgres
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - /home/user/ai-stack/postgresql/data:/var/lib/postgresql/data
      - /home/user/ai-stack/postgresql/init-scripts:/docker-entrypoint-initdb.d  # extensions setup
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    shm_size: 1g
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
```

I am on the `proxy` network as well

I am getting the error pg_hba.conf. But it works fine if I change the image to official Postgres.
